[program:spruik-pulse]
command=/bin/sh -c "mkdir -p /run/spruik-pulse && chown pulse:pulse /run/spruik-pulse && exec pulseaudio --system --daemonize=no --exit-idle-time=-1 --disallow-exit --disable-shm --load='module-native-protocol-unix socket=/run/spruik-pulse/native auth-anonymous=1'"
autostart=true
autorestart=true
startretries=10
priority=5
user=root
redirect_stderr=true
stdout_logfile=/var/log/spruik-pulse.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2

