[program:signal-cli-json-rpc-1]
process_name=signal-cli-json-rpc-1
command=/usr/bin/signal-cli-native --output=json --config /home/.local/share/signal-cli/ daemon --tcp 127.0.0.1:6001
autostart=true
autorestart=true
startretries=10
user=signal-api
directory=/usr/bin/
redirect_stderr=true
stdout_logfile=/var/log/signal-cli-json-rpc-1/out.log
stderr_logfile=/var/log/signal-cli-json-rpc-1/err.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
numprocs=1
